package com.rpl.olympic.register.model;

public enum Contry {

		AND("Andorra, Principality of "),

		ARE("United Arab Emirates "),

		AFG("Afghanistan"),

		ATG("Antigua and Barbuda"),
		AIA("Anguilla"),
		ALB("Albania, People's Socialist Republic of "),
		ARM("Armenia "),
		ANT("Netherlands Antilles "),
		AGO("Angola, Republic of"),
		ATA("Antarctica (the territory South of 60 deg S)"),
		ARG("Argentina, Argentine Republic"),
		ASM("American Samoa "),
		AUT("Austria, Republic of "),
		AUS("Australia, Commonwealth of "),
		ABW("Aruba "),
		ALA("\u00c5land Islands "),
		AZE("Azerbaijan, Republic of"),
		BIH("Bosnia and Herzegovina "),
		BRB("Barbados"),
		BGD("Bangladesh, People's Republic of"),
		BEL("Belgium, Kingdom of"),
		BFA("Burkina Faso "),
		BGR("Bulgaria, People's Republic of"),
		BHR("Bahrain, Kingdom of"),
		BDI("Burundi, Republic of "),
		BEN("Benin, People's Republic of"),
		BLM("Saint Barth\u00e9lemy"),
		BMU("Bermuda "),
		BRN("Brunei Darussalam"),
		BOL("Bolivia, Republic of "),
		BES("Bonaire, Sint Eustatius and Saba"),
		BRA("Brazil, Federative Republic of"),
		BHS("Bahamas, Commonwealth of the "),
		BTN("Bhutan, Kingdom of "),
		BVT("Bouvet Island (Bouvetoya)"),
		BWA("Botswana, Republic of"),
		BLR("Belarus "),
		BLZ("Belize"),
		CAN("Canada"),
		CCK("Cocos (Keeling) Islands"),
		COD("Congo, Democratic Republic of"),
		CAF("Central African Republic "),
		COG("Congo, People's Republic of"),
		CHE("Switzerland, Swiss Confederation"),
		CIV("Cote D'Ivoire, Ivory Coast, Republic of the "),
		COK("Cook Islands "),
		CHL("Chile, Republic of "),
		CMR("Cameroon, United Republic of "),
		CHN("China, People's Republic of"),
		COL("Colombia, Republic of"),
		CRI("Costa Rica, Republic of"),
		SCG("Serbia and Montenegro"),
		CUB("Cuba, Republic of"),
		CPV("Cape Verde, Republic of"),
		CUW("Cura\u00e7ao "),
		CXR("Christmas Island "),
		CYP("Cyprus, Republic of"),
		CZE("Czech Republic "),
		DEU("Germany "),
		DJI("Djibouti, Republic of"),
		DNK("Denmark, Kingdom of"),
		DMA("Dominica, Commonwealth of"),
		DOM("Dominican Republic "),
		DZA("Algeria, People's Democratic Republic of"),
		ECU("Ecuador, Republic of "),
		EST("Estonia "),
		EGY("Egypt, Arab Republic of"),
		ESH("Western Sahara "),
		ERI("Eritrea "),
		ESP("Spain, Spanish State "),
		ETH("Ethiopia"),
		FIN("Finland, Republic of "),
		FJI("Fiji, Republic of the Fiji Islands"),
		FLK("Falkland Islands (Malvinas)"),
		FSM("Micronesia, Federated States of "),
		FRO("Faeroe Islands "),
		FRA("France, French Republic"),
		GAB("Gabon, Gabonese Republic "),
		GBR("United Kingdom of Great Britain & N. Ireland"),
		GRD("Grenada "),
		GEO("Georgia "),
		GUF("French Guiana"),
		GGY("Guernsey"),
		GHA("Ghana, Republic of "),
		GIB("Gibraltar "),
		GRL("Greenland "),
		GMB("Gambia, Republic of the"),
		GIN("Guinea, Revolutionary People's Rep'c of "),
		GLP("Guadaloupe"),
		GNQ("Equatorial Guinea, Republic of"),
		GRC("Greece, Hellenic Republic"),
		SGS("South Georgia and the South Sandwich Islands"),
		GTM("Guatemala, Republic of "),
		GUM("Guam"),
		GNB("Guinea-Bissau, Republic of "),
		GUY("Guyana, Republic of"),
		HKG("Hong Kong, Special Administrative Region of Chin"),
		HMD("Heard and McDonald Islands "),
		HND("Honduras, Republic of"),
		HRV("Hrvatska (Croatia) "),
		HTI("Haiti, Republic of "),
		HUN("Hungary, Hungarian People's Republic"),
		IDN("Indonesia, Republic of "),
		IRL("Ireland "),
		ISR("Israel, State of "),
		IMN("Isle of Man"),
		IND("India, Republic of "),
		IOT("British Indian Ocean Territory (Chagos Archipela"),
		IRQ("Iraq, Republic of"),
		IRN("Iran, Islamic Republic of"),
		ISL("Iceland, Republic of "),
		ITA("Italy, Italian Republic"),
		JEY("Jersey"),
		JAM("Jamaica "),
		JOR("Jordan, Hashemite Kingdom of "),
		JPN("Japan "),
		KEN("Kenya, Republic of "),
		KGZ("Kyrgyz Republic"),
		KHM("Cambodia, Kingdom of "),
		KIR("Kiribati, Republic of"),
		COM("Comoros, Union of the"),
		KNA("St. Kitts and Nevis"),
		PRK("Korea, Democratic People's Republic of"),
		KOR("Korea, Republic of "),
		KWT("Kuwait, State of "),
		CYM("Cayman Islands "),
		KAZ("Kazakhstan, Republic of"),
		LAO("Lao People's Democratic Republic"),
		LBN("Lebanon, Lebanese Republic "),
		LCA("St. Lucia "),
		LIE("Liechtenstein, Principality of"),
		LKA("Sri Lanka, Democratic Socialist Republic of "),
		LBR("Liberia, Republic of "),
		LSO("Lesotho, Kingdom of"),
		LTU("Lithuania "),
		LUX("Luxembourg, Grand Duchy of "),
		LVA("Latvia"),
		LBY("Libyan Arab Jamahiriya "),
		MAR("Morocco, Kingdom of"),
		MCO("Monaco, Principality of"),
		MDA("Moldova, Republic of "),
		MNE("Montenegro, Republic of"),
		MAF("Saint Martin "),
		MDG("Madagascar, Republic of"),
		MHL("Marshall Islands "),
		MKD("Macedonia, the former Yugoslav Republic of"),
		MLI("Mali, Republic of"),
		MMR("Myanmar "),
		MNG("Mongolia, Mongolian People's Republic "),
		MAC("Macao, Special Administrative Region of China "),
		MNP("Northern Mariana Islands "),
		MTQ("Martinique"),
		MRT("Mauritania, Islamic Republic of "),
		MSR("Montserrat"),
		MLT("Malta, Republic of "),
		MUS("Mauritius "),
		MDV("Maldives, Republic of"),
		MWI("Malawi, Republic of"),
		MEX("Mexico, United Mexican States"),
		MYS("Malaysia"),
		MOZ("Mozambique, People's Republic of"),
		NAM("Namibia "),
		NCL("New Caledonia"),
		NER("Niger, Republic of the "),
		NFK("Norfolk Island "),
		NGA("Nigeria, Federal Republic of "),
		NIC("Nicaragua, Republic of "),
		NLD("Netherlands, Kingdom of the"),
		NOR("Norway, Kingdom of "),
		NPL("Nepal, Kingdom of"),
		NRU("Nauru, Republic of "),
		NIU("Niue, Republic of"),
		NZL("New Zealand"),
		OMN("Oman, Sultanate of "),
		PAN("Panama, Republic of"),
		PER("Peru, Republic of"),
		PYF("French Polynesia "),
		PNG("Papua New Guinea "),
		PHL("Philippines, Republic of the "),
		PAK("Pakistan, Islamic Republic of"),
		POL("Poland, Republic of Poland "),
		SPM("St. Pierre and Miquelon"),
		PCN("Pitcairn Island"),
		PRI("Puerto Rico"),
		PSE("Palestinian Territory, Occupied "),
		PRT("Portugal, Portuguese Republic"),
		PLW("Palau "),
		PRY("Paraguay, Republic of"),
		QAT("Qatar, State of"),
		REU("Reunion "),
		ROU("Romania, Socialist Republic of"),
		SRB("Serbia, Republic of"),
		RUS("Russian Federation "),
		RWA("Rwanda, Rwandese Republic"),
		SAU("Saudi Arabia, Kingdom of "),
		SLB("Solomon Islands"),
		SYC("Seychelles, Republic of"),
		SDN("Sudan, Democratic Republic of the "),
		SWE("Sweden, Kingdom of "),
		SGP("Singapore, Republic of "),
		SHN("St. Helena"),
		SVN("Slovenia"),
		SJM("Svalbard & Jan Mayen Islands "),
		SVK("Slovakia (Slovak Republic)"),
		SLE("Sierra Leone, Republic of"),
		SMR("San Marino, Republic of"),
		SEN("Senegal, Republic of "),
		SOM("Somalia, Somali Republic "),
		SUR("Suriname, Republic of"),
		SSD("South Sudan"),
		STP("Sao Tome and Principe, Democratic Republic of "),
		SLV("El Salvador, Republic of "),
		SXM("Sint Maarten (Dutch part)"),
		SYR("Syrian Arab Republic "),
		SWZ("Swaziland, Kingdom of"),
		TCA("Turks and Caicos Islands "),
		TCD("Chad, Republic of"),
		ATF("French Southern Territories"),
		TGO("Togo, Togolese Republic"),
		THA("Thailand, Kingdom of "),
		TJK("Tajikistan"),
		TKL("Tokelau (Tokelau Islands)"),
		TLS("Timor-Leste, Democratic Republic of "),
		TKM("Turkmenistan "),
		TUN("Tunisia, Republic of "),
		TON("Tonga, Kingdom of"),
		TUR("Turkey, Republic of"),
		TTO("Trinidad and Tobago, Republic of"),
		TUV("Tuvalu"),
		TWN("Taiwan, Province of China"),
		TZA("Tanzania, United Republic of "),
		UKR("Ukraine "),
		UGA("Uganda, Republic of"),
		UMI("United States Minor Outlying Islands"),
		USA("United States of America "),
		URY("Uruguay, Eastern Republic of "),
		UZB("Uzbekistan"),
		VAT("Holy See (Vatican City State)"),
		VCT("St. Vincent and the Grenadines"),
		VEN("Venezuela, Bolivarian Republic of "),
		VGB("British Virgin Islands "),
		VIR("US Virgin Islands"),
		VNM("Viet Nam, Socialist Republic of "),
		VUT("Vanuatu "),
		WLF("Wallis and Futuna Islands"),
		WSM("Samoa, Independent State of"),
		YEM("Yemen "),
		MYT("Mayotte "),
		ZAF("South Africa, Republic of"),
		ZMB("Zambia, Republic of"),
		ZWE("Zimbabwe");

	private String contryName;

	private Contry(String contryName) {
		this.contryName = contryName;
	}

	public String getContryName() {
		return this.contryName;
	}
}
